# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9nyplYPeqtSAZaii3tU1WEqb9Uc070h
"""

# Reading Pdf files
import PyPDF2
data = open('CSE FYP.pdf','rb')
reader = PyPDF2.PdfFileReader(data)
print(reader.numPages)
page = reader.getPage(4)
print(page.extractText())
data.close()

# Reading text files
dataText = open('tech.txt','r')
print(dataText.read())


#Reading CSV files

import numpy as np
import pandas as pd

dataCsv = pd.read_csv('/content/Book.csv')
dataCsv.head()
dataCsv.columns
dataCsv.shape